#include<stdio.h>
#include<conio.h>
void main()
{
clrscr();
printf(" horoscope prediction");
int a;
scanf("%d",&a);
if (a==1)
{
printf("you are very lucky your crush is going to reply you in next few days if you give sid 1000 rs ");
}
if (a==2)
{
printf("your are not that lucky still who knows what will happen to you stay away from    water ");
}
if (a==3)
{
printf("your sugar level is low i think all you need is teravi ki bundi");
}
if (a==4)
{
printf("this is not going to change your luck go and study ******");
}
if (a==5)
{
printf("dump this shit lets go on a date");
}
getch();
}